### ISSUE TITLE
How to do multi head attention, but the shape of q, k, and v is different?

### ISSUE THREAD

**Issue by Originlightwkp** [Taited/sgdiff#3]
The SCA moudle adopt semantic features form clip and text features form clip, the Q is only from text, K and V are added by text and image. And your picture in the paper shows that the Q, K, V have different shape, so how to do Q@K? Is this is your SCA code?

 `
    def forward(self, img, text_emb):
        if self.clip_norm:
            img = (img + 1) / 2
            img = F.batch_norm(img, self.mean.to(self.device),
                               self.std.to(self.device))
            img = F.interpolate(img, (224, 224))
        image_features = self.model(img)
        if self.last_layer_proj:
            image_features = torch.einsum('bld,ds->bls', image_features,
                                          self.model.proj)
        if self.cross_attn is not None:
            emb_features = self.cross_attn(
                text_emb.permute(0, 2, 1),
                image_features.permute(0, 2, 1)).permute(0, 2, 1)
        if self.skip_module is not None:
            if self.learned_length:
                residual = self.skip_module(emb_features.permute(0, 2, 1))
                residual = residual.permute(0, 2, 1)
            else:
                residual = self.skip_module(emb_features)
            text_emb += residual
        return text_emb
`

**Comment by Taited** [comment]
Thanks for your issue.  Indeed, there is a distinct dimensionality associated with the length of Q, and K and V. When applying the attention mechanism, the Q@K operation occurs in the width dimension, where they align. For example, the operation is as follows: ``(batch, length_m, dimension) @ (batch, length_n, dimension) -> (batch, length_m, length_n)``. You can find an implementation of cross-attention here:
https://github.com/Taited/sgdiff/blob/12487a10556a41647a857e5d9fe3f7d310f0c196/mmagic/models/editors/sgdiff/clip_modules.py#L103
