### ISSUE TITLE
Results are not good

### ISSUE THREAD

**Issue by Originlightwkp** [Taited/sgdiff#4]
i use this picture
![9](https://github.com/Taited/sgdiff/assets/55913193/b9832e21-a3da-4f2d-b884-48366563e8ad)
and use Vincent van Gogh’s Starry Night as text prompt
the result is not as good as expected
![results](https://github.com/Taited/sgdiff/assets/55913193/94d05f69-114a-4723-8579-1b45e31e0b47)

**Comment by Taited** [comment]
Hi, please note that this work is designed to use image input to condition the **style** and text input to condition the **content**. If you wish to condition on 'Starry Night', it would be better to use an image as the input. I have just updated a demo, which you can find [here](https://github.com/Taited/sgdiff#inference-code-now-available-). Please take a look.
